parameters:
    psi.ui.helper.slots.class:  Psi\UIBundle\Helper\SlotsHelper
    psi.ui.helper.datatable.class: Psi\UIBundle\Helper\DataTableHelper

services:
    
    psi.ui.helper.datatable:
        class: "%psi.ui.helper.datatable.class%"
        tags:
            - { name: templating.helper, alias: table }    
    
    psi.ui.helper.slots:
        class: "%psi.ui.helper.slots.class%"
        arguments:
            - true
        tags:
            - { name: templating.helper, alias: UI }