services:

    psi.api.event.api.request.subscriber:
        class: Psi\ApiBundle\Event\ApiRequestSubscriber
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_subscriber }
