parameters:

services:

    psi.app.request.static.authenthication:
        class: Psi\AppBundle\Request\StaticAuthentication

    psi.app.request.factory:
        class: Psi\ApiBundle\Request\Factory\RequestFactory
        arguments:
            - "@psi.app.request.static.authenthication"

    
    psi.app.denormalizer.runePage:
        class: Psi\AppBundle\Serializer\Denormalizer\RunePageDenormalizer
        arguments:
            - "@doctrine.orm.entity_manager"
            
    psi.app.denormalizer.masteryPage:
        class: Psi\AppBundle\Serializer\Denormalizer\MasteryPageDenormalizer
        arguments:
            - "@doctrine.orm.entity_manager"            


    psi.app.manager.api.response.manager:
        class: Psi\AppBundle\Manager\ApiResponseManager
        calls:
            - method: addResponseHandler
              arguments: 
                  - "@psi.app.denormalizer.runePage"
            - method: addResponseHandler
              arguments: 
                  - "@psi.app.denormalizer.masteryPage"                  